CREATE TABLE `user` (
  `id`       INTEGER PRIMARY KEY AUTOINCREMENT,
  `username` VARCHAR(32) NOT NULL,
  `passWord` VARCHAR(32) NOT NULL,
  `age`      INTEGER
);

INSERT INTO user (username, passWord, age) VALUES ('kobe', 'abc123', 23);
INSERT INTO user (id, username, passWord, age) VALUES (3, 'james', 'abc123', 24);


CREATE TABLE SERVER (
  ID             INTEGER PRIMARY KEY AUTO_INCREMENT,
  IP             VARCHAR(20)  NOT NULL,
  PORT           VARCHAR(10)  NOT NULL,
  USERNAME       VARCHAR(50)  NOT NULL,
  PASSWORD       VARCHAR(50)  NOT NULL,
  SERVER_VERSION VARCHAR(200) NOT NULL,
  DATA_VERSION   VARCHAR(200) NOT NULL,
  IS_ACTIVE      BOOLEAN             DEFAULT 0,
  UPDATE_TIME    VARCHAR(30),
  DESCIPTION     VARCHAR(50)
);

CREATE TABLE TASK (
  TASKNO     INTEGER PRIMARY KEY AUTO_INCREMENT,
  TASK_NAME   VARCHAR(50),
  STATUS     INTEGER,
  PROGESS    INTEGER,
  STATUS_INFO VARCHAR(100),
  CREATE_TIME VARCHAR(30),
  START_TIME  VARCHAR(30),
  END_TIME    VARCHAR(30),
  SERVERID   INTEGER     NOT NULL,
  FILE_PATH  VARCHAR(100) NOT NULL,
  SOURCE_VERSION VARCHAR(30) NOT NULL,
  TARGET_VERSION VARCHAR(30) NOT NULL,
  CONSTRAINT FOREIGN KEY (SERVERID) REFERENCES SERVER (ID)
);
