CREATE TABLE `user` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT ,
  `username` varchar(32) NOT NULL ,
  `passWord` varchar(32) NOT NULL ,
  `age` INTEGER
);

insert into user(username, passWord, age) values('kobe', 'abc123', 23);
insert into user(id, username, passWord, age) values(3, 'james', 'abc123', 24);

create table TASK (
	TASKNO INTEGER PRIMARY KEY AUTOINCREMENT,
	JOBNUM VARCHAR(10) NOT NULL,
	TASKNAME VARCHAR(50),
	STATUS INTEGER,
	STATUSINFO VARCHAR(100),
	CREATETIME VARCHAR(30),
	STARTTIME VARCHAR(30),
	ENDTIME VARCHAR(30),
	SERVERID NOT NULL REFERENCES SERVER(ID)
);

CREATE TABLE SERVER(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	DESCIPTION VARCHAR(50),
	IP VARCHAR(20) NOT NULL,
	PORT VARCHAR(10) NOT NULL,
	VERSION VARCHAR(200) NOT NULL
);
